// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspnetCoreMvcFull.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241127094723_addingPlannerDetailsTable")]
    partial class addingPlannerDetailsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Days", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("days");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Monday"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tuesday"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wednesday"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thursday"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Friday"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Saturday"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sunday"
                        });
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.PlannerDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DayId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_id");

                    b.Property<int>("PlannerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("planner_id");

                    b.Property<int>("ProductionTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("production_total");

                    b.Property<int>("daysId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("plannersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("daysId");

                    b.HasIndex("plannersId");

                    b.ToTable("planner_details");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Planners", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("week");

                    b.HasKey("Id");

                    b.ToTable("planners");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.PlannerDetails", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Days", "days")
                        .WithMany("plannerDetails")
                        .HasForeignKey("daysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspnetCoreMvcFull.Models.Planners", "planners")
                        .WithMany("PlannerDetails")
                        .HasForeignKey("plannersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("days");

                    b.Navigation("planners");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Days", b =>
                {
                    b.Navigation("plannerDetails");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Planners", b =>
                {
                    b.Navigation("PlannerDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
